// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment-specific .env file first so APP_ENV is available.
// Vercel injects NODE_ENV=production at build time; locally the file
// (.env.production, .env.staging, .env.development, or .env) is used.
const nodeEnv = process.env.NODE_ENV || "development";
dotenv.config({ path: `.env.${nodeEnv}`, override: false });
dotenv.config({ path: ".env", override: false });

const APP_ENV = (process.env.APP_ENV || nodeEnv || "development").toLowerCase();
const DB_URL = process.env.DATABASE_URL ?? "";
const BUILD_PHASE = process.env.NEXT_PHASE === "phase-production-build";

const isProduction = APP_ENV === "production";
const schemaFile = isProduction ? "prisma/schema.pg.prisma" : "prisma/schema.prisma";

// During the Vercel build phase, DATABASE_URL may not be available as a
// build-time env var. Provide a placeholder PostgreSQL URL so prisma generate
// can determine the correct provider from schema.pg.prisma. The real URL is
// injected by the Vercel platform at runtime.
const DATASOURCE_URL = BUILD_PHASE && isProduction
  ? "postgresql://placeholder:ignored@localhost:5432/postgres"
  : (DB_URL || (isProduction ? "" : "file:./prisma/dev.db"));

if (!BUILD_PHASE && !DB_URL && APP_ENV === "production") {
  console.warn(
    "╔══════════════════════════════════════════════════════════════════╗\n" +
    "║  WARNING: DATABASE_URL is not set. Using fallback for generate. ║\n" +
    "║  Set DATABASE_URL in your production deployment env vars.       ║\n" +
    "╚══════════════════════════════════════════════════════════════════╝"
  );
}

// Skip datasource validation during the build phase — the actual DATABASE_URL
// will be available at runtime via Vercel environment variables.
if (!BUILD_PHASE && DB_URL) {
  const isSqlite = DB_URL.startsWith("file:");
  const isPostgres = DB_URL.startsWith("postgresql://") || DB_URL.startsWith("postgres://");

  let isDevDatabase = false;
  let isStagingDatabase = false;
  let isProdDatabase = false;

  if (isSqlite) {
    isDevDatabase = DB_URL.includes("dev.db");
    isStagingDatabase = DB_URL.includes("staging.db");
    isProdDatabase = DB_URL.includes("prod.db") && !isDevDatabase;
  } else if (isPostgres) {
    const dbName = DB_URL.split("/").pop()?.split("?")[0] ?? "";
    isDevDatabase = dbName.includes("dev");
    isStagingDatabase = dbName.includes("staging");
    isProdDatabase = dbName.includes("prod") || (dbName.length > 0 && !isDevDatabase && !isStagingDatabase);
  } else {
    isProdDatabase = APP_ENV === "production";
    isStagingDatabase = APP_ENV === "staging";
    isDevDatabase = APP_ENV === "development";
  }

  if (APP_ENV === "development" && isProdDatabase) {
    throw new Error(
      "Development environment targets a production database. " +
      "Check your DATABASE_URL in .env.development."
    );
  }

  if (APP_ENV === "production" && !isProdDatabase) {
    throw new Error(
      "Production environment does not target a production DB. " +
      "Check your DATABASE_URL in .env.production or deployment vars."
    );
  }

  if (APP_ENV === "staging" && isProdDatabase) {
    throw new Error(
      "Staging environment targets a production database. " +
      "Check your DATABASE_URL in staging deployment variables."
    );
  }
}

export default defineConfig({
  schema: schemaFile,
  migrations: {
    path: isProduction ? "prisma/pg-migrations" : "prisma/migrations",
  },
  datasource: {
    url: DATASOURCE_URL,
  },
});
