// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const APP_ENV = (process.env.APP_ENV || process.env.NODE_ENV || "development").toLowerCase();
const DB_URL = process.env.DATABASE_URL ?? "";

const isProduction = APP_ENV === "production";
const schemaFile = isProduction ? "prisma/schema.pg.prisma" : "prisma/schema.prisma";

// For PostgreSQL production, the fallback is empty (must be set in env).
// For SQLite dev, fall back to the local dev database.
const DATASOURCE_URL = DB_URL || (isProduction ? "" : "file:./prisma/dev.db");

if (!DB_URL && APP_ENV === "production") {
  console.warn(
    "╔══════════════════════════════════════════════════════════════════╗\n" +
    "║  WARNING: DATABASE_URL is not set. Using fallback for generate. ║\n" +
    "║  Set DATABASE_URL in your production deployment env vars.       ║\n" +
    "╚══════════════════════════════════════════════════════════════════╝"
  );
}

if (DB_URL) {
  const isSqlite = DB_URL.startsWith("file:");
  const isPostgres = DB_URL.startsWith("postgresql://") || DB_URL.startsWith("postgres://");

  let isDevDatabase = false;
  let isStagingDatabase = false;
  let isProdDatabase = false;

  if (isSqlite) {
    isDevDatabase = DB_URL.includes("dev.db");
    isStagingDatabase = DB_URL.includes("staging.db");
    isProdDatabase = DB_URL.includes("prod.db") && !isDevDatabase;
  } else if (isPostgres) {
    const dbName = DB_URL.split("/").pop()?.split("?")[0] ?? "";
    isDevDatabase = dbName.includes("dev");
    isStagingDatabase = dbName.includes("staging");
    isProdDatabase = dbName.includes("prod") || (dbName.length > 0 && !isDevDatabase && !isStagingDatabase);
  } else {
    isProdDatabase = APP_ENV === "production";
    isStagingDatabase = APP_ENV === "staging";
    isDevDatabase = APP_ENV === "development";
  }

  if (APP_ENV === "development" && isProdDatabase) {
    console.error(
      "╔══════════════════════════════════════════════════════════════════╗\n" +
      "║  FATAL: Development environment targets a production database.  ║\n" +
      "║  Check your DATABASE_URL in .env.development.                   ║\n" +
      "╚══════════════════════════════════════════════════════════════════╝"
    );
    process.exit(1);
  }

  if (APP_ENV === "production" && !isProdDatabase) {
    console.error(
      "╔══════════════════════════════════════════════════════════════════╗\n" +
      "║  FATAL: Production environment does not target a production DB. ║\n" +
      "║  Check your DATABASE_URL in .env.production or deployment vars. ║\n" +
      "╚══════════════════════════════════════════════════════════════════╝"
    );
    process.exit(1);
  }

  if (APP_ENV === "staging" && isProdDatabase) {
    console.error(
      "╔══════════════════════════════════════════════════════════════════╗\n" +
      "║  FATAL: Staging environment targets a production database.      ║\n" +
      "║  Check your DATABASE_URL in staging deployment variables.       ║\n" +
      "╚══════════════════════════════════════════════════════════════════╝"
    );
    process.exit(1);
  }
}

export default defineConfig({
  schema: schemaFile,
  migrations: {
    path: isProduction ? "prisma/pg-migrations" : "prisma/migrations",
  },
  datasource: {
    url: DATASOURCE_URL,
  },
});
