export enum UserRole {
  OWNER = "OWNER",

  SUPER_ADMIN = "SUPER_ADMIN",

  DEVELOPER = "DEVELOPER",

  BILLING_MANAGER = "BILLING_MANAGER",

  COMMUNITY_MANAGER = "COMMUNITY_MANAGER",

  SUPPORT_MANAGER = "SUPPORT_MANAGER",

  SUPPORT_AGENT = "SUPPORT_AGENT",

  MODERATOR = "MODERATOR",

  ANALYST = "ANALYST",
}
